/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#1a146b",
        "surface-bright": "#faf8ff",
        "outline-variant": "#c8c5d3",
        "surface": "#faf8ff",
        "primary-container": "#312e81",
        "secondary-container": "#fe932c",
        "surface-container": "#eaedff",
        "surface-container-highest": "#dae2fd",
        "on-primary-fixed": "#100563",
        "on-tertiary-fixed": "#00201d",
        "inverse-primary": "#c3c0ff",
        "outline": "#777682",
        "secondary-fixed-dim": "#ffb77d",
        "error-container": "#ffdad6",
        "surface-tint": "#5654a8",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d2d9f4",
        "tertiary": "#002a26",
        "on-secondary": "#ffffff",
        "inverse-surface": "#283044",
        "surface-variant": "#dae2fd",
        "on-secondary-fixed-variant": "#6e3900",
        "on-secondary-fixed": "#2f1500",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#005049",
        "primary-fixed": "#e2dfff",
        "on-surface-variant": "#474651",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ffdcc3",
        "tertiary-fixed": "#89f5e7",
        "on-error": "#ffffff",
        "on-secondary-container": "#663500",
        "surface-container-high": "#e2e7ff",
        "surface-container-low": "#f2f3ff",
        "inverse-on-surface": "#eef0ff",
        "on-primary-fixed-variant": "#3e3c8f",
        "on-background": "#131b2e",
        "on-tertiary-container": "#44b5a8",
        "primary-fixed-dim": "#c3c0ff",
        "on-surface": "#131b2e",
        "secondary": "#904d00",
        "tertiary-container": "#00423c",
        "tertiary-fixed-dim": "#6bd8cb",
        "on-primary-container": "#9c9af4",
        "background": "#faf8ff",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.375rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "1rem",
        "margin": "3rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        display: ["'Manrope'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      }
    },
  },
  plugins: [],
}
